server:
  port: 8081
#  port: ${PORT:${SERVER_PORT:0}} # Paso1: generar puertos aleatorios

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/microservicios
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: USUARIO-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
#  profiles:
#    active: prod

#eureka:
#  instance:
#    prefer-ip-address: true
##    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Paso2: generar puertos aleatorios
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka